### ISSUE TITLE
pagina de dashboard 

### ISSUE THREAD

**Issue by Gabriel-neto** [Gabriel-neto/BlackBox-ERP#14]

**Comment by pedro-v-bezerra** [comment]
![dashboard(aba_fornecedores)](https://github.com/Gabriel-neto/BlackBox-ERP/assets/62081545/f2ae391b-a4d5-460a-914d-43844458cd15)
![dashboard(aba_perfil)](https://github.com/Gabriel-neto/BlackBox-ERP/assets/62081545/69e17222-98e4-40d9-855e-22713f398749)
![dashboard(aba_estoque)](https://github.com/Gabriel-neto/BlackBox-ERP/assets/62081545/815b56f5-3e29-4857-9fb9-b4c1f429fd3a)
