### ISSUE TITLE
autenticação no firebase

### ISSUE THREAD

**Issue by Gabriel-neto** [Gabriel-neto/BlackBox-ERP#19]
autenticação no Firebase

**Comment by gfranca96** [comment]
Foi criado uma pasta chamada services, composta por dois arquivos AuthService.js e FirebaseConfig.js. 

Na AuthService foi criado a função Login e Logout.

Na FirebaseConfig está a chave de autenticação junto com as configurações necessárias.

No contexto foi criada uma função para passar email e senha para autenticação.

Na ScreenLogin foi criada uma função onSubmit para enviar email e senha do formulário.

Foi feito feito também as validações dos campos usuário e senha.
