### ISSUE TITLE
Verificação de produtos 

### ISSUE THREAD

**Issue by Gabriel-neto** [Gabriel-neto/BlackBox-ERP#49]
na criação de produtos não tem autenticação sendo assim podendo cria fornecedor e produto vazios.

**Comment by iamedusm** [comment]
criado a validação na tela de produtos para impedir cadastro de produtos vazios / nulos

![tela validação produto](https://github.com/Gabriel-neto/BlackBox-ERP/assets/63604055/50c43704-4b26-40be-b222-44344851a4d5)
