### ISSUE TITLE
Criação da página do sistema de login / cadastro no Figma

### ISSUE THREAD

**Issue by iamedusm** [Gabriel-neto/BlackBox-ERP#6]
Criação do modelo da página do login / cadastro no figma

**Comment by pedro-v-bezerra** [comment]
![Image](https://user-images.githubusercontent.com/62081545/232942428-d80cc1c1-8b40-43d5-a692-2ccbfe407407.png)

**Comment by pedro-v-bezerra** [comment]
![Image](https://user-images.githubusercontent.com/62081545/232942471-8fd79e03-989e-43ba-97a3-a7c64839ce2c.png)
