### ISSUE TITLE
Criação da página de login / cadastro no react

### ISSUE THREAD

**Issue by iamedusm** [Gabriel-neto/BlackBox-ERP#7]
Criação da página de login / cadastro no react

**Comment by pedro-v-bezerra** [comment]
![Image](https://user-images.githubusercontent.com/62081545/232942151-dacd7894-e62f-4521-8c4c-076968cd8394.png)

**Comment by pedro-v-bezerra** [comment]
![Image](https://user-images.githubusercontent.com/62081545/232942202-b037b96d-690b-41b2-852d-8c90391c1dc3.png)

**Comment by Gabriel-neto** [comment]
layout aprovado entre os integrantes
